# http://goreleaser.com
project_name: jpresolver

builds:
- id: jpdownloader
  binary: jpdownloader
  main: ./cmd/jpdownloader/main.go
  goarch:
  - amd64
- id: jpresolver
  binary: jpresolver
  main: ./cmd/jpresolver/main.go
  goarch:
  - amd64

archives:
- id: jpdownloader
  builds:
  - jpdownloader
  name_template: 'jpdownloader_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  files:
    - README.md
  replacements:
    amd64: x86_64
- id: jpresolver
  builds:
  - jpresolver
  name_template: 'jpresolver_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  files:
    - README.md
  replacements:
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .FullCommit }}-{{ .Tag }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
