name: Build and Test

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Bazel build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: run
      uses: ngalaiko/bazel-action@0.29.0
      with:
        args: build //...
  test:
    name: Bazel test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: run
      uses: ngalaiko/bazel-action@0.29.0
      with:
        args: test //...

