name: Continuous Deployment
on:
  push: 
    tags:
    - 2*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build targets
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel build //...
  test:
    name: Test
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Test targets
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel test //...
  publish:
    name: Publish
    needs: [ build, test ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Unshallow
      run: git fetch --prune --unshallow
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.GCR_BITNAMI_LABS }}
        DOCKER_USERNAME: _json_key
        DOCKER_REGISTRY_URL: https://gcr.io
    - name: Publish jenkins-plugins-resolver (tag)
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel run //docker/jpresolver:push_tag
    - name: Publish jenkins-plugins-resolver (latest)
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel run //docker/jpresolver:push_latest
    - name: Publish jenkins-plugins-downloader (tag)
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel run //docker/jpdownloader:push_tag
    - name: Publish jenkins-plugins-downloader (latest)
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel run //docker/jpdownloader:push_latest

