name: Continuous Integration
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build targets
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel build //...
  test:
    name: Test
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Test targets
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel test //...
  publish:
    name: Publish
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.GCR_BITNAMI_LABS }}
        DOCKER_USERNAME: _json_key
        DOCKER_REGISTRY_URL: https://gcr.io
    - name: Publish jenkins-plugins-resolver (tag)
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel //docker/jpresolver:push_tag
    - name: Publish jenkins-plugins-resolver (latest)
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel //docker/jpresolver:push_latest
    - name: Publish jenkins-plugins-downloader (tag)
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel //docker/jpdownloader:push_tag
    - name: Publish jenkins-plugins-downloader (latest)
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel //docker/jpdownloader:push_latest

