name: Continuous Integration
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build targets
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel build //...
  test:
    name: Test
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Test targets
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel test //...
