name: Continuous Integration
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build targets
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel build //...
  test:
    needs: [build]
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Test targets
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: bazel test //...
  publish:
    needs: [build, test]
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Docker Login
      uses: actions/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.GCR_BITNAMI_LABS }}
        DOCKER_USERNAME: _json_key
        DOCKER_REGISTRY_URL: https://gcr.io
    - name: Publish targets
      uses: docker://l.gcr.io/google/bazel:0.29.1
      with:
        entrypoint: /bin/bash
        args: echo Testing

