name: Continuous Deployment
on:
  push: 
    tags:
    - 2*

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Unshallow
      run: git fetch --prune --unshallow
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Publish release
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Login GCR
      run: docker login https://gcr.io -u _json_key -p "${GCR_BITNAMI_LABS}"
      env:
        DOCKER_CONFIG: ${GITHUB_WORKSPACE}/.docker/${GITHUB_RUN_ID}
        GCR_BITNAMI_LABS: ${{ secrets.GCR_BITNAMI_LABS }}
    - name: Publish containers
      uses: docker://l.gcr.io/google/bazel:2.2.0
      with:
        entrypoint: /bin/bash
        args: |
          ./tools/bazel-docker-push.sh
          ./tools/bazel-docker-push-latest.sh
      env:
        DOCKER_CONFIG: ${GITHUB_WORKSPACE}/.docker/${GITHUB_RUN_ID}
